# build only master branch on commit's
# all other branches build on PullRequest creation
branches:
  only:
    - master

language: rust

rust:
# build nightly only for the time beeing
  - nightly

matrix:
  fast_finish: true
  include:
    - name: "RusPiRo Loader Kernel"
      install:
        - sudo apt-get install gcc-aarch64-linux-gnu
        - cargo install cargo-xbuild
        - cargo install cargo-make
        - rustup target add aarch64-unknown-linux-gnu
        - rustup component add rust-src
        - rustup component add llvm-tools-preview
        - sed -i 's/path.*=.*\".*", //g' Cargo.toml
      script: cargo make pi3 --profile travis
