# build only master branch on commit's
# all other branches build on PullRequest creation
branches:
  only:
    - master

language: rust

rust:
# build nightly only for the time beeing
  - nightly

matrix:
  include:
    - name: "RusPiRo Host App"
      script: cd dev-host && cargo build

    - name: "RusPiRo Loader Kernel"
      install:
        - sudo apt-get install gcc-aarch64-linux-gnu gcc-aarch64-linux-gnu
        - cargo install cargo-xbuild
        - rustup target add aarch64-unknown-linux-gnu
        - rustup component add rust-src
        - sudo chmod ugo+x dev-target/build.sh
      script: cd dev-target && sed -i 's/path.*=.*\".*", //g' Cargo.toml && ./build.sh travis

    - name: "RusPiRo Test Kernel 64Bit"
      install:
        - sudo apt-get install gcc-aarch64-linux-gnu gcc-aarch64-linux-gnu
        - cargo install cargo-xbuild
        - rustup target add aarch64-unknown-linux-gnu
        - rustup component add rust-src
        - sudo chmod ugo+x test-kernel/build.sh
      script: cd test-kernel && ./build.sh 64

    - name: "RusPiRo Test Kernel 32Bit"
      install:
        - sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
        - cargo install cargo-xbuild
        - rustup target add armv7-unknown-linux-gnueabihf
        - rustup component add rust-src
        - sudo chmod ugo+x test-kernel/build.sh
      script: cd test-kernel && sed -i 's/path.*=.*\".*", //g' Cargo.toml && ./build.sh 32
