[package]
name = "ruspiro-loader"
authors = ["Andre Borrmann <pspwizard@gmx.de>"]
version = "0.0.1" # remember to update html_root_url
description = "Raspbeyrr Pi bare metal bootloader kernel"
license = "Apache-2.0"
repository = "https://github.com/RusPiRo/ruspiro-loader/tree/v0.0.1"
documentation = "https://docs.rs/ruspiro-loader/0.0.1"
readme = "README.md"
keywords = ["RusPiRo", "baremetal", "raspberrypi", "bootloader"]
categories = ["no-std", "embedded"]
edition = "2018"

[badges]
travis-ci = { repository = "RusPiRo/ruspiro-loader", branch = "master" }
maintenance = { status = "actively-developed" }


[[bin]]
name = "kernel7"
path = "./src/loader.rs"

[dependencies]
ruspiro-boot = { version = "0.1.1", features = ["with_panic", "with_exception"] }
ruspiro-singleton = "0.1.0"
ruspiro-gpio = "0.1.0"
ruspiro-mailbox = "0.1.0"
ruspiro-uart = "0.1.0"
ruspiro-interrupt = "0.1.0"
ruspiro-timer = "0.1.0"
ruspiro-allocator = "0.1.1"
ruspiro-console = "0.1.1"

[features]
defauls = ["ruspiro_pi3"]
ruspiro_pi3 = []

[patch.crates-io]
ruspiro-boot = { path = "../ruspiro-boot" } #, features = ["singlecore"] }
ruspiro-console = { path = "../ruspiro-console" }
ruspiro-uart = { path = "../ruspiro-uart" }
ruspiro-mailbox = { path = "../ruspiro-mailbox" }