name: CI

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  build:
    name: Compile The Crate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [pi3, pi4_low, pi4_high]

    steps:
      # Checkout the current code from github into the CI machine
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install aarch64 gcc toolchain
        run: sudo apt-get install -y gcc-aarch64-linux-gnu

      # install toolchain based on rust-toolchain file
      - name: Install Rust Nightly and Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-09-05
          profile: minimal
          components: rust-src, llvm-tools-preview
          target: aarch64-unknown-none
          override: true

      - name: Install Cargo Make
        uses: davidB/rust-cargo-make@v1
        with:
          version: 'latest'

      - if: ${{ github.event_name != 'pull_request' }}
        name: Remove patches if not a PR build
        run: |
          sed -i "/{^\[patch\.crates-io\] /{:a;N;/\Z}/!ba};/^ruspiro-.*\(git\|path\).*/d" Cargo.toml;
          cat Cargo.toml

      - name: Compile
        run: cargo make -t ${{ matrix.platform }} --profile pipeline
